host:
  name: gilani-starter.herokuapp.com
  port: 80
smtp:
  address: <%= ENV['SMTP_HOST'] %>
  port: <%= ENV['SMTP_PORT'] %>
  username: <%= ENV['SMTP_USERNAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
